[env:bluepill]
platform = ststm32
board = bluepill_f103c8
framework = stm32cube
upload_protocol = stlink
lib_deps =
  jeeh
  Wasm3=symlink://../../../../source

build_flags =
  -Dd_m3FixedHeap=8192
  -Dd_m3CodePageAlignSize=512
  -Dd_m3EnableValidation=0
  -Dd_m3HasFloat=0
  -Dd_m3HasRefTypes=0
  -Os -Wfatal-errors
